#!/usr/bin/env bash
set -ueo pipefail

echo "--- :wrench: Configuring tools with asdf"
pushd "$path" || exit 1
if [ ! -f ".tool-versions" ]; then
  echo "No .tool-versions found! Aborting."
  exit 1
fi

echo "~~~ :jigsaw: Installing asdf plugins"
while IFS="" read -r p || [ -n "$p" ]
do
  plugin_name="${p%% *}"
  plugin_version="${p#* }"
  asdf plugin-add "$plugin_name" || true
  asdf reshim "$plugin_name" "$plugin_version" || true
done < .tool-versions

echo "~~~ :toolbox: Installing asdf tool versions"
asdf install


popd

export ASDF_DIR
export PATH
