#!/usr/bin/env bash
set -ueo pipefail

ASDF_VERSION="v0.14.0"
path=$(echo "${BUILDKITE_PLUGIN_ASDF_PATH:-.}" | sed 's/^\///') # strip prefixed slashes

function install_asdf() {
  echo "~~~ :git: Cloning asdf"
  git clone https://github.com/asdf-vm/asdf.git ~/.asdf --branch "$ASDF_VERSION" || true

  # shellcheck source=/dev/null
  . "$HOME"/.asdf/asdf.sh
}

echo "--- :wrench: Configuring tools with asdf"
pushd "$path" || exit 1
if [ ! -f ".tool-versions" ]; then
  echo "No .tool-versions found! Aborting."
  exit 1
fi

if ! command -v asdf &>/dev/null; then
	echo "asdf not found. Installing"
	install_asdf
fi

echo "~~~ :jigsaw: Installing asdf plugins"
while IFS="" read -r p || [ -n "$p" ]
do
  plugin_name="${p%% *}"
  asdf plugin-add "$plugin_name" || true
done < .tool-versions

echo "~~~ :toolbox: Installing asdf tool versions"
asdf install

echo "~~~ :jigsaw: Reshiming asdf plugins"
while IFS="" read -r p || [ -n "$p" ]
do
  plugin_name="${p%% *}"
  plugin_version="${p#* }"
  asdf reshim "$plugin_name" "$plugin_version" || true
done < .tool-versions

popd

export ASDF_DIR
export PATH
